server:
  port: 8802

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: eureka02
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8802/eureka